Expand getNormalizedPath() to use throughout the project
OpenAWE-Project/OpenAWE pull request #24
Opened 2023-01-30 20:18 UTC by maaxxaam

This PR should be able to resolve #15. `getNormalizedPath()` function, created during #21, now also removes "runtimedata\pc" and "d:/data" from the path.

2023-01-30 20:22 UTC, maaxxaam commented
Ok, that's weird. CI have failed because vcpkg can't download bullet.

2023-01-31 08:43 UTC, Nostritius reviewed
Some style reviews. I have not yet tested it, so there might be more comments

2023-01-31 08:43 UTC, Nostritius commented on src/common/path.cpp
> +namespace Common {
I would prefer this to stay in AWE, since this path normalization is very specific to these games.

2023-01-31 08:43 UTC, Nostritius commented on src/graphics/mesh_binfol.cpp
> +#include <src/common/path.h>
For every include on files inside the repository (except everything in 3rdparty) use #include "" instead of #include <>

2023-01-31 08:43 UTC, Nostritius commented on src/common/path.cpp
> +	if (lower.find("runtimedata\\pc") == 0) lower.replace(0, 14, "d:");
Could you create a common "replace" function in strutil.h? since we will likely use this more often, this could be beneficial.

2023-01-31 08:43 UTC, Nostritius commented on src/common/path.cpp
> +using std::string;
I prefer using the full namespace instead of "using" statements

2023-02-04 21:53 UTC, Nostritius commented
Just one thing, could you add unit tests for the path normalization and the replace function?

2023-02-05 10:27 UTC, maaxxaam commented
Will do that once I figure out why tests for MSVC build fail - it's not visible in a PR now, but that came up when I ran a CI job on a fork.

2023-02-24 20:27 UTC, Nostritius requested changes
There is one problem I addressed in a comment which makes the level loading in awan fail and needs to be addressed. Apart there are only two smaller style issues

2023-02-24 20:27 UTC, Nostritius commented on src/awe/rmdparchive.cpp
> +	return Common::replace(path, "d:/data", "");
I have tested  and it seems this line causes problems when loading archives in episode.cpp in line 49-53. Changing this to "d:/data/" would fix this. I do not know why this is happening, but I would like to stick with the convention of paths not starting with a /.

2023-02-24 20:27 UTC, Nostritius commented on src/graphics/mesh_binfol.cpp
> +#include "src/graphics/mesh_binfol.h"
A new line between these two includes is missing

2023-02-24 20:27 UTC, Nostritius commented on src/awe/path.h
> + * - removing runtimedata\pc and d:/data from path
It would be nice to have a parameter and return documentation in the comment

2023-02-26 09:13 UTC, merged

2023-02-26 09:14 UTC, Nostritius commented
Merged, Thanks