Add support for binfnt v7
OpenAWE-Project/OpenAWE pull request #45
Opened 2024-07-01 18:47 UTC by Jackkal

This PR adds support for binfnt v7 files and adds support for uncompressed RGB DDS textures.

This allows loading of the font/fixedsys.binfnt file as used in Control.
Binfnt v7 files can include kerning information but this info is ignored for now (it is not used in the fixedsys font).

Verified by using the Control fixedsys.binfnt as an asset when running Alan Wake AN with OpenAWE.

2024-07-01 19:40 UTC, Jackkal commented
Practical note: I will be offline for next 1-2 weeks.

2024-07-13 11:18 UTC, Nostritius requested changes
We are good to go for this apart from the comment. For the long term, I would like the binfnt file loading in its own file class in the awe part and have a loader similar to the ones for meshes in the graphics part.

2024-07-13 11:18 UTC, Nostritius commented on src/graphics/images/dds.cpp
> -		size_t dataSize = std::max(16u, ((width + 3u) / 4u) * ((height + 3u) / 4u) * 16u);
You can get the image data size over the getImageSize from the base class and won't need to implement this here

2024-07-14 10:06 UTC, Nostritius approved these changes

2024-07-14 11:13 UTC, merged